apiVersion: v1
kind: ServiceAccount
metadata:
    name: orleansclient
    namespace: kubetest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: orleansclient
rules:
    - apiGroups:
          - orleans.dot.net
      resources:
          - silos
          - clusterversions
      verbs:
          - get
          - list
          - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: orleansclient
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: orleansclient
subjects:
    - kind: ServiceAccount
      name: orleansclient
      namespace: kubetest
