apiVersion: v1
kind: ServiceAccount
metadata:
  name: orleansclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleansclient
rules:
- apiGroups:
    - orleans.dot.net
  resources:
    - silos
    - clusterversions
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orleansclient
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orleansclient
subjects:
- kind: ServiceAccount
  name: orleansclient
