apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-silo
  labels:
    app: kubesilo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesilo
  template:
    metadata:
      labels:
        app: kubesilo
    spec:
      serviceAccountName: orleanssilo
      containers:
        - name: orleanssilo
          image: kubesilo:latest
          imagePullPolicy: Never
