apiVersion: v1
kind: ServiceAccount
metadata:
  name: orleanssilo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orleanssilo
rules:
- apiGroups:
    - orleans.dot.net
  resources:
    - silos
    - clusterversions
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orleanssilo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orleanssilo
subjects:
- kind: ServiceAccount
  name: orleanssilo
