apiVersion: v1
kind: ServiceAccount
metadata:
    name: orleanssilo
    namespace: kubetest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: orleanssilo
rules:
    - apiGroups:
          - orleans.dot.net
      resources:
          - silos
          - clusterversions
      verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: orleanssilo
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: orleanssilo
subjects:
    - kind: ServiceAccount
      name: orleanssilo
      namespace: kubetest
