name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # - uses: engineerd/setup-kind@v0.3.0
      #   with:
      #     config: .github/workflows/kind.yml
      # - name: Setup Kube API
      #   run: kubectl proxy &
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.100
      - name: Build
        run: dotnet build --configuration Release
      # - name: Test
      #   run: dotnet test --configuration Release --no-build
