name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100
    - name: Pack
      working-directory: src/Orleans.Clustering.Kubernetes
      run: dotnet pack --configuration Release -p:Version=${GITHUB_REF##*/v}
    - name: Push
      working-directory: src/Orleans.Clustering.Kubernetes/bin/Release
      run: |
        dotnet nuget push Orleans.Clustering.Kubernetes.*.nupkg --skip-duplicate -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Create Release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
